### ISSUE TITLE
Segfault when a request is received and the server instance is deleted at the same time

### ISSUE THREAD

**Issue by AtsushiMorinaga** [sony/nmos-cpp#189]
It is required to re-create the nmos::server instance when listener port settings(IP address, port, etc) are changed.
Segmentation fault may happen if a request comes in the middle of tear down process.

As a result of investigation, I found that
1. The request handler has a lambda callback function that has capture of `api_router` by reference.
  https://github.com/sony/nmos-cpp/blob/master/Development/nmos/api_utils.cpp#L666
2. When a request is received, the handler is invoked and an async task is generated.
  https://github.com/sony/nmos-cpp/blob/master/Development/cpprest/api_router.cpp#L66
3. Then the instance of nmos::server is deleted, resources are destructed but the async task is not cannceled by destructor.
4. Segfault when the task is invoked because it has the dangling reference of `api_router`.

* Backtrace

```
#0  0x004823d4 in bool std::__detail::__regex_algo_impl<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, char, std::regex_traits<char>, (std::__detail::_RegexExecutorPolicy)0, true>(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >&, std::basic_regex<char, std::regex_traits<char> > const&, std::regex_constants::match_flag_type) ()
#1  0x0047c7dc in web::http::experimental::listener::api_router::operator()(web::http::http_request, web::http::http_response, std::string const&, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, std::_List_iterator<web::http::experimental::listener::api_router::route>) ()
#2  0x0047cd48 in std::_Function_handler<pplx::task<bool> (bool), web::http::experimental::listener::api_router::operator()(web::http::http_request, web::http::http_response, std::string const&, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, std::_List_iterator<web::http::experimental::listener::api_router::route>)::{lambda(bool)#1}>::_M_invoke(std::_Any_data const&, bool) ()
#3  0x0047e2a4 in pplx::details::_PPLTaskHandle<bool, pplx::task<bool>::_ContinuationTaskHandle<bool, bool, web::http::experimental::listener::api_router::operator()(web::http::http_request, web::http::http_response, std::string const&, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, std::_List_iterator<web::http::experimental::listener::api_router::route>)::{lambda(bool)#1}, std::integral_constant<bool, false>, pplx::details::_TypeSelectorAsyncTask>, pplx::details::_ContinuationTaskHandleBase>::invoke() const
    ()
#4  0x00220330 in pplx::details::_TaskProcHandle::_RunChoreBridge (_Parameter=0x1b970500)
    at cpprestsdk-2.10.15/Release/include/pplx/pplx.h:113
#5  0x002be280 in boost::_bi::list1<boost::_bi::value<void*> >::operator()<void (*)(void*), boost::_bi::list0> (f=<synthetic pointer>: <optimized out>, 
    a=<synthetic pointer>..., this=<synthetic pointer>) at boost_1_69_0/boost/bind/bind.hpp:259
#6  boost::_bi::bind_t<void, void (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > >::operator() (this=<synthetic pointer>)
    at boost_1_69_0/boost/bind/bind.hpp:1294
#7  boost::asio::asio_handler_invoke<boost::_bi::bind_t<void, void (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > > > (
    function=<synthetic pointer>...) at boost_1_69_0/boost/asio/handler_invoke_hook.hpp:69
#8  boost_asio_handler_invoke_helpers::invoke<boost::_bi::bind_t<void, void (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > >, boost::_bi::bind_t<void, void (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > > > (context=<synthetic pointer>..., function=<synthetic pointer>...)
    at boost_1_69_0/boost/asio/detail/handler_invoke_helpers.hpp:37
#9  boost::asio::detail::handler_work<boost::_bi::bind_t<void, void (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > >, boost::asio::system_executor>::complete<boost::_bi::bind_t<void, void (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > > > (this=<synthetic pointer>, 
    handler=<synthetic pointer>..., function=<synthetic pointer>...) at boost_1_69_0/boost/asio/detail/handler_work.hpp:82
#10 boost::asio::detail::completion_handler<boost::_bi::bind_t<void, void (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > > >::do_complete (
    owner=0x1b741b50, base=0xf50840) at boost_1_69_0/boost/asio/detail/completion_handler.hpp:70
#11 0x002aaec4 in boost::asio::detail::scheduler_operation::complete (bytes_transferred=0, ec=..., owner=0x1b741b50, this=<optimized out>)
    at boost_1_69_0/boost/asio/detail/scheduler_operation.hpp:40
#12 boost::asio::detail::scheduler::do_run_one (ec=..., this_thread=..., lock=..., this=0x1b741b50)
    at boost_1_69_0/boost/asio/detail/impl/scheduler.ipp:401
#13 boost::asio::detail::scheduler::run (this=0x1b741b50, ec=...) at boost_1_69_0/boost/asio/detail/impl/scheduler.ipp:154
#14 0x002be674 in boost::asio::io_context::run (this=0x847c94 <(anonymous namespace)::initialize_shared_threadpool(unsigned int)::uninit_threadpool+4>)
    at boost_1_69_0/boost/asio/impl/io_context.ipp:62
#15 (anonymous namespace)::threadpool_impl::thread_start (arg=0x847c90 <(anonymous namespace)::initialize_shared_threadpool(unsigned int)::uninit_threadpool>)
    at cpprestsdk-2.10.15/Release/src/pplx/threadpool.cpp:79
#16 (anonymous namespace)::threadpool_impl::<lambda()>::operator() (__closure=<optimized out>)
    at cpprestsdk-2.10.15/Release/src/pplx/threadpool.cpp:64
#17 boost::asio::detail::posix_thread::func<(anonymous namespace)::threadpool_impl::add_thread()::<lambda()> >::run(void) (this=<optimized out>)
    at boost_1_69_0/boost/asio/detail/posix_thread.hpp:86
#18 0x002a507c in boost::asio::detail::boost_asio_detail_posix_thread_function (arg=0x1b976610)
    at boost_1_69_0/boost/asio/detail/impl/posix_thread.ipp:74
#19 0x36994f14 in start_thread (arg=0x1a6fef40) at pthread_create.c:339
#20 0x3691e740 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:89 from /lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

* Steps to reproduce

1. Add sleep(10) to this line. https://github.com/sony/nmos-cpp/blob/master/Development/cpprest/api_router.cpp#L88
2. Modify [nmos-cpp-node/main.cpp](https://github.com/sony/nmos-cpp/blob/master/Development/nmos-cpp-node/main.cpp#L98) as follows

```c++
// Set up the node server
{ //!!
auto node_server = nmos::experimental::make_node_server(node_model, node_implementation, log_model, gate);

...

nmos::server_guard node_server_guard(node_server);

slog::log<slog::severities::info>(gate, SLOG_FLF) << "Ready for connections";
sleep(10); //!! curl http://127.0.0.1:3212/x-nmos
} //!! node_server.api_routers is cleared in ~server()

// Wait for a process termination signal
nmos::details::wait_term_signal();
```

3. Run ./nmos-cpp-node
4. curl http://localhost:3212/x-nmos within 10 seconds.

* System Information
  * Debian10 GNU/Linux
  * boost 1.69.0 
  * cpprestsdk 2.10.15

Please tell me an appropriate way to change listener port settings during execution if you know.

https://github.com/sony/nmos-cpp/issues/107 sounds great!

**Comment by AtsushiMorinaga** [comment]
@garethsb @lo-simon @jonathan-r-thorpe Thank you very much!
